### ISSUE TITLE
'Basic Usage' snippet does not work

### ISSUE THREAD

**Issue by Jacyle** [mortada/fredapi#24]
The following snippet doesn't work for me:

`from fredapi import Fred`
`fred = Fred(api_key='insert api key here')`
`data = fred.get_series('SP500')`

I get the following error:

from fredapi import Fred

Traceback (most recent call last):

  File "<ipython-input-5-7658b7c1a8ce>", line 1, in <module>
    from fredapi import Fred

  File "C:\Users\Jake\Documents\Analytic Productions\fredapi.py", line 8, in <module>
    from fredapi import Fred

ImportError: cannot import name 'Fred'

**Comment by mortada** [comment]
could you please provide a bit more context - which version of `fredapi` are you using, and which OS? thanks!

**Comment by Jacyle** [comment]
mb, I'm using fredapi 0.4.2 and Windows7/python 3.5

The import statement is not finding the module.
